# -*- coding: utf-8 -*-
"""Spell-Checker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x8SX-zIrpr64pqiQs1wZw_Rm_iEdhMqf
"""

from textblob import TextBlob 

t = 1
while t:
    a = input("Enter the word to be checked:- ")	 
    print("original text: "+str(a))     

    b = TextBlob(a)  


    print("corrected text: "+str(b.correct()))