# -*- coding: utf-8 -*-
"""BMI-Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KmCvWVSSzwyfmETnznjPfOdZ3WO_d6Ta
"""

#function to calculate the BMI on the height and weight inputs by user.

def bmi(height,mass):
	b_index = mass/(height**2)
	return b_index

height = float(input("Enter the height in meters:"))
mass = float(input("Enter the weight in kg:"))
b_index = bmi(height,mass)
print("Your BMI is:",format(b_index))