# -*- coding: utf-8 -*-
"""YouTube-Downloader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wt0jIPHF3bcESFFdYczwKrUwd2Behe_m
"""

! pip install pytube3

! pip install git+http://github.com/pytube/pytube

from pytube import YouTube

YouTube('https://www.youtube.com/watch?v=07d2dXHYb94').streams.first().download()

url = "https://www.youtube.com/watch?v=07d2dXHYb94"

yt = YouTube(url)

yt.streams.first().download()